name: ruta_segura_app
description: "App de viaje inteligente y seguro para La Paz y El Alto (prototipo hackathon)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  geolocator: ^13.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  speech_to_text: ^7.0.0
  url_launcher: ^6.3.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  shared_preferences: ^2.3.2
  http: ^1.6.0
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
